name: TestWasmLib
description: Exercise several aspects of WasmLib

# ##################################

events:
  test:
    name: String
    address: Address

# ##################################

structs:
  Location:
    x: Int32
    y: Int32

# ##################################

typedefs:
  ### Array
  StringArray: String[]
  Int32Array: Int32[]
  Int64Array: Int64[]
  Uint64Array: Uint64[]
  BytesArray: Bytes[]
  AddressArray: Address[]
  AgentIDArray: AgentID[]
  ChainIDArray: ChainID[]
  ColorArray: Color[]
  HashArray: Hash[]
  HnameArray: Hname[]
  RequestIDArray: RequestID[]
  ### Map
  StringMap: map[String]String
  Int32Map: map[Int32]Int32
  Int64Map: map[Int64]Int64
  Uint64Map: map[Uint64]Uint64
  BytesMap: map[Bytes]Bytes
  AddressMap: map[Address]Address
  AgentIDMap: map[AgentID]AgentID
  ChainIDMap: map[ChainID]ChainID
  ColorMap: map[Color]Color
  HashMap: map[Hash]Hash
  HnameMap: map[Hname]Hname
  RequestIDMap: map[RequestID]RequestID
  Longitude: map[Int32]Location

# ##################################

state:
  # basic value datatypes
  stringMapOfArrays: map[String]StringArray
  stringMapOfMaps: map[String]StringMap
  stringArrayOfMaps: StringMap[]
  stringArrayOfArrays: StringArray[]
  # contracts-specific value datatypes
  addrMapOfArrays: map[Address]AddressArray
  addrMapOfMaps: map[Address]AddressMap
  addrArrayOfMaps: AddressMap[]
  addrArrayOfArrays: AddressArray[]
  # Other
  random: Uint64
  latLong: map[Int32]Longitude
  # LongID: map[Longitude]Int32 # FIXME Map with struct key would cause error
  

# ##################################

funcs:
  mapOfArraysAppend:
    params:
      name: String
      value: String

  mapOfArraysAddrAppend:
    params:
      nameAddr: Address
      valueAddr: Address

  arrayOfArraysAppend:
    params:
      index: Uint32
      value: String[]

  arrayOfArraysAddrAppend:
    params:
      index: Uint32
      valueAddr: Address[]

  arrayOfArraysSet:
    params:
      index0: Uint32
      index1: Uint32
      value: String

  arrayOfArraysAddrSet:
    params:
      index0: Uint32
      index1: Uint32
      valueAddr: Address

  # Clear all the arrays of the array
  arrayOfArraysClear:
  # Clear all the arrays of the array
  arrayOfArraysAddrClear:

  mapOfArraysClear:
    params:
      name: String
  
  mapOfArraysAddrClear:
    params:
      nameAddr: Address

  mapOfArraysSet:
    params:
      index: Uint32
      name: String
      value: String

  mapOfArraysAddrSet:
    params:
      index: Uint32
      nameAddr: Address
      valueAddr: Address

  mapOfMapsClear:
    params:
      name: String

  mapOfMapsSet:
    params:
      name: String
      key: String
      value: String

  arrayOfMapsClear:

  arrayOfMapsSet:
    params:
      index: Uint32
      key: String
      value: String

  paramTypes:
    params:
      address: Address?
      agentID: AgentID?
      bool: Bool?
      bytes: Bytes?
      chainID: ChainID?
      color: Color?
      hash: Hash?
      hname: Hname?
      int8: Int8?
      int16: Int16?
      int32: Int32?
      int64: Int64?
      param=this: map[String]Bytes? // special hook to be able to pass key/values as raw bytes
      requestID: RequestID?
      string: String?
      uint8: Uint8?
      uint16: Uint16?
      uint32: Uint32?
      uint64: Uint64?

  random:

  takeAllowance:

  takeBalance:
    results:
      iotas: Uint64

  triggerEvent:
    params:
      name: String
      address: Address

# ##################################

views:
  mapOfArraysLength:
    params:
      name: String
    results:
      length: Uint32

  mapOfArraysAddrLength:
    params:
      nameAddr: Address
    results:
      length: Uint32

  arrayOfArraysLength:
    results:
      length: Uint32

  arrayOfArraysValue:
    params:
      index0: Uint32
      index1: Uint32
    results:
      value: String

  arrayOfArraysAddrLength:
    results:
      length: Uint32

  arrayOfArraysAddrValue:
    params:
      index0: Uint32
      index1: Uint32
    results:
      valueAddr: Address

  mapOfArraysValue:
    params:
      index: Uint32
      name: String
    results:
      value: String

  mapOfArraysAddrValue:
    params:
      index: Uint32
      nameAddr: Address
    results:
      valueAddr: Address

  mapOfMapsValue:
    params:
      name: String
      key: String
    results:
      value: String

  arrayOfMapsValue:
    params:
      index: Uint32
      key: String
    results:
      value: String

  blockRecord:
    params:
      blockIndex: Uint32
      recordIndex: Uint32
    results:
      record: Bytes

  blockRecords:
    params:
      blockIndex: Uint32
    results:
      count: Uint32

  iotaBalance:
    results:
      iotas: Uint64

  getRandom:
    results:
      random: Uint64
