name: CoreAccounts
description: Core chain account ledger contract
structs: {}
typedefs: {}
state: {}
funcs:
  deposit:
  transferAllowanceTo:
    params:
      agentID=a: AgentID
      forceOpenAccount=c: Bool
  withdraw: {}
  harvest:
    params:
      forceMinimumIotas=f: Uint64
  foundryCreateNew:
    params:
      tokenScheme=t: TokenScheme
      tokenTag=g: TokenTag
    results:
      foundrySN: Bytes
  foundryDestroy:
    params:
      foundrySN: Uint32
  foundryOutput: {}
  foundryModifySupply:
    params:
      foundrySN: Uint32
      supplyDeltaAbs: BigInt
      destroyTokens: Bool

views:
  balance:
    params:
      agentID=a: AgentID
    results:
      balances: map[Color]Uint64
  totalAssets:
    results:
      assets: map[Color]Uint64
  accounts:
    results:
      allAccounts=C: map[AccountID]Bool
  getAccountNonce:
    params:
      foundrySN: Uint32
    results:
      accountNonce=n: Uint64
  getNativeTokenIDs:
    results:
      mapping=G: map[TokenID]Bytes
  foundryOutput:
    results:
      foundryOutputBin: Bytes
  accountNFTs:
    params:
      agentID=a: AgentID
    results:
      nftIDs=i: Bytes
  nftData:
    params:
      nftID=z: Bytes
    results:
      nftData=e: Bytes
