name: CoreAccounts
description: Core chain account ledger contract
structs: {}
typedefs: {}
state: {}
funcs:
  deposit: {}
  transferAllowanceTo:
    params:
      agentID=a: AgentID
      forceOpenAccount=c: Bool
  withdraw: {}
  harvest:
    params:
      forceMinimumIotas=f: Uint64
  foundryCreateNew:
    params:
      tokenScheme=t: TokenScheme
      tokenTag=g: TokenTag
    results:
      foundrySN=s: Uint32
  foundryDestroy:
    params:
      foundrySN: Uint32
  foundryModifySupply:
    params:
      foundrySN: Uint32
      supplyDeltaAbs: BigInt
      destroyTokens: Bool

views:
  balance:
    params:
      agentID=a: AgentID
    results:
      balances=this: map[TokenID]Uint64
  totalAssets:
    results:
      assets=this: map[TokenID]Uint64
  accounts:
    results:
      allAccounts=this: map[TokenID]Uint64
  getAccountNonce:
    params:
      foundrySN: Uint32
    results:
      accountNonce=n: Uint64
  getNativeTokenIDs:
    results:
      mapping=G: map[TokenID]Bytes
  foundryOutput:
    results:
      foundryOutputBin=b: Bytes
  foundryOutput:
    params:
      foundrySN: Uint32
  accountNFTs:
    params:
      agentID=a: AgentID
    results:
      nftIDs=i: Bytes
  nftData:
    params:
      nftID=z: Bytes
    results:
      nftData=e: Bytes
