name: Test

on:
  push:
    branches: [develop, artifacts]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup dependencies
        run: sudo apt-get install libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: make build

      - name: Test
        run: make test-short-no-wasm

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Generate SC files
        run: |
           go install ./tools/schema
           cd contracts/wasm
           for dir in */ ; do
                cd ${dir};
                schema -go -rust -ts;
                cd ..;
           done
           cd gascalibration
           for dir in */ ; do
                cd ${dir};
                schema -go;
                cd ..;
           done
           cd ..
      - name: golangci-lint in SC
        run: |
           curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.47.2
           cd contracts/wasm
           ../../bin/golangci-lint run --fix --timeout 5m0s
           
      - name: Run global scope golangci-lint
        run: |
          ./bin/golangci-lint run --timeout 5m0s
