name: Contracts Test

on:
  pull_request:
    branches: [develop]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to the directory
        uses: actions/checkout@v3

      - name: install golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: install tinygo
        # only work on x86_64
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.23.0/tinygo_0.23.0_amd64.deb
          sudo dpkg -i tinygo_0.23.0_amd64.deb
          export PATH=$PATH:/usr/local/bin
      
      - name: install rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: stable

      - name: install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: install Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install schema
        run: |
          cd contracts/wasm && go install ../../tools/schema
      - name: run builds
        run: |
          cd contracts/wasm && bash all_build.sh
      - name: run tests
        run: |
          cd contracts/wasm && go test ./... &&
          cd ../../packages/vm/ && go test ./...

          

